import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{BookOpen,CheckCircle2,Gift,Shirt,Star}from'lucide-react';import'./style.css';
const kids=['Kiegan','Levi','Will'];
function App(){const[user,setUser]=useState(null);const[pin,setPin]=useState('');if(!user)return <main className="login"><section><h1>TEAM MILLER</h1><p>Working together. Serving our family. Honoring God.</p><div className="profiles">{[...kids,'Parent'].map(n=><button onClick={()=>setUser(n)} key={n}>{n}</button>)}</div><small>Select your profile to continue. PIN setup is the next connection step.</small></section></main>;return <><header><div><b>TEAM MILLER</b><span> MISSION BOARD</span></div><button onClick={()=>setUser(null)}>Log out</button></header><main className="wrap"><h2>Hey, {user}! 👋</h2>{user==='Parent'?<Parent/>:<Child name={user}/>}</main></>}
function Child({name}){return <><div className="stats"><Card title="Mission Points" value="0" icon={<Star/>}/><Card title="Reading Points" value="0" icon={<BookOpen/>}/></div><h3>Today's Missions</h3><div className="panel">{['Make Bed','Bedroom Picked Up','Dirty Clothes in Hamper','Family 10-Minute Cleanup','Be Respectful & Have a Good Attitude','Read for 20 Minutes'].map(x=><label className="mission" key={x}><input type="checkbox" disabled/><span>{x}</span><b>+1</b></label>)}</div><div className="grid"><Box icon={<Shirt/>} title="Laundry" text="Your laundry assignment will appear here."/><Box icon={<Gift/>} title="Next Reward" text="25 points — Pick Dessert"/><Box icon={<CheckCircle2/>} title="Bonus Mission" text="Submit Bible reading, prayer, kindness and more."/><Box icon={<BookOpen/>} title="Reading" text="Find a book and take a TEAM MILLER quiz."/></div></>}
function Parent(){return <><div className="stats"><Card title="Kiegan" value="0 MP / 0 RP"/><Card title="Levi" value="0 MP / 0 RP"/><Card title="Will" value="0 MP / 0 RP"/></div><div className="grid"><Box title="Mission Control" text="Daily missions, corrections and weekly assignments"/><Box title="Approvals" text="Laundry and Bonus Mission approvals"/><Box title="Rewards" text="Redeem unlocked family rewards"/><Box title="Books & Quizzes" text="Upload and manage TEAM MILLER quizzes"/><Box title="Reports" text="Month, quarter, school year, calendar year and all time"/><Box title="Settings" text="Family timezone and PIN management"/></div></>}
function Card({title,value,icon}){return <div className="card">{icon}<small>{title}</small><strong>{value}</strong></div>}function Box({icon,title,text}){return <div className="box">{icon}<h3>{title}</h3><p>{text}</p></div>}createRoot(document.getElementById('root')).render(<App/>);


createRoot(document.getElementById('root')).render(<App />);
